### ISSUE TITLE
Remove the last line in /R/phyloseq_beta.R

### ISSUE THREAD

**Issue by vincentvendius** [fconstancias/DivComAnalyses#4]
Error in source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_beta.R") : 
  https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_beta.R:3732:1: unexpected '}'
3731: }
3732: }

**Comment by fconstancias** [comment]
I was working on implementing NTI bNTI metrics (e.g., https://www.pnas.org/action/downloadSupplement?doi=10.1073%2Fpnas.1414261112&file=pnas.201414261SI.pdf). Thanks @vincentvendius. It should be fixed now.
